import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;
import java.sql.*;

public class DemoServlet extends HttpServlet
{


public void doGet(HttpServletRequest request,HttpServletResponse response)throws ServletException,IOException
{
System.out.println("Servlet is invoked,generating response...");

response.setContentType("text/html");
PrintWriter out=response.getWriter();
out.println("This response is generated by servlet..<br>");
System.out.println("returning control from the servlet.");

}
}
