import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;


public class MyFilter implements Filter
{

FilterConfig config;

public void init(FilterConfig config)
{
this.config=config;
}

public void doFilter(ServletRequest request,ServletResponse response,FilterChain chain)throws ServletException,IOException
{
System.out.println("Filter is invoked, generating response...");
response.setContentType("text/html");
PrintWriter out=response.getWriter();
out.println("<b>It is generated by a filter.</b><br>");
System.out.println("Transfering control to the next resource...");
chain.doFilter(request,response);
System.out.println("Control is received back in filter...");
out.println("<b> It is appended by the filter.</b>");
System.out.println("returning control from the filter..");
}

public void destroy()
{}

}
